### ISSUE TITLE
Feature Request: Only show timer when on Leagues Worlds

### ISSUE THREAD

**Issue by Fiffers** [DominickCobb-rs/undying-retribution-timer#3]
It'd be nice if the timer was only shown while logged in to a leagues world. I tend to swap back and forth constantly between leagues and the main game, and I'd prefer to not need to turn the plugin on and off each time.

Thanks for making this!

**Comment by DominickCobb-rs** [comment]
Added in 89c2b8d652a7f4f63caf08eb1c18b53f92d7b7e3
