### ISSUE TITLE
"Only show on cooldown" option doesn't work on a freshly launched client

### ISSUE THREAD

**Issue by gabrielamboss** [DominickCobb-rs/undying-retribution-timer#7]
The overlay is displayed (without a timer) every time I log in the first time on a fresh client, despite the "Only show on cooldown" option being enabled. Toggling the option off and on again makes it disappear and work as expected.

It also appears on accounts that don't have last stand unlocked, though that is minor.

**Comment by DominickCobb-rs** [comment]
I'll look into the first issue in a few hours. Should be a quick fix.

For the latter, I'm not interested in tracking that at this time as it's a temporary gamemode, but if I get bored I might look into it.

**Comment by gabrielamboss** [comment]
Thanks! And yeah, that makes sense. I kind of bundled them together because I expect the second issue to be solved when the first one is implemented. If it only shows up when triggered (and not on first login), I imagine accounts that don't have it will never get the overlay

**Comment by DominickCobb-rs** [comment]
Yeah I suppose it would in fact be solved, but only in for those with this config setting.

**Comment by DominickCobb-rs** [comment]
Resolved in afdc1818d2c5430627e2d23134ff3e80b57dd46b
